# Generated by Django 3.0.14 on 2023-03-31 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230330_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendorder',
            old_name='qty',
            new_name='quantity',
        ),
    ]
